### ISSUE TITLE
Game asset tool - Export asset doesn't work on *nix systems

### ISSUE THREAD

**Issue by kabukunz** [Linko-3D/AssetGen#2]
Hello, there's a double slash hardcoded path that's preventing export to work on *nix systems. 

<img width="947" alt="screen shot 2017-10-15 at 18 11 10" src="https://user-images.githubusercontent.com/33091053/31997800-9ac77d9a-b98d-11e7-88d1-ff42590cf5c2.png">

I tested this fix on Mac, should work fine on Ubuntu and the like; need test in windows.
Change GT_user_interface.py class ExpObj into:

[ExpObj.txt](https://github.com/Linko-3D/AssetGen/files/1414491/ExpObj.txt)

And you need to add 

import sys 

at the beginning of GT_user_interface.py

**Comment by paddywwoof** [comment]
better to use os.path.join
os is already imported
